{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f3988da",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import transformers\n",
    "import torch\n",
    "import pandas as pd\n",
    "import json\n",
    "\n",
    "# ------------------------\n",
    "# Load dataset\n",
    "# ------------------------\n",
    "df = pd.read_csv(\"your_dataset.csv\")  # Assumes there is a column named \"text\"\n",
    "\n",
    "# ------------------------\n",
    "# Load model once\n",
    "# ------------------------\n",
    "model_path = \"/gpfs1/llm/llama-3.2-hf/Meta-Llama-3.2-3B-Instruct\"\n",
    "classifier = transformers.pipeline(\n",
    "    \"text-generation\",\n",
    "    model=model_path,\n",
    "    model_kwargs={\"torch_dtype\": torch.bfloat16},\n",
    "    device_map=\"auto\"\n",
    ")\n",
    "\n",
    "# ------------------------\n",
    "# Classification function\n",
    "# ------------------------\n",
    "def classify_row(text):\n",
    "    prompt = (\n",
    "        \"You are an assistant trained to identify stances about infant feeding methods in a given text.\\n\\n\"\n",
    "        \"Definitions:\\n\"\n",
    "        \"- \\\"Stance\\\": A belief or opinion (e.g., \\\"breastfeeding is best\\\").\\n\"\n",
    "        \"- \\\"Behavior\\\": An action (e.g., \\\"I breastfed for a year\\\") — not a stance by itself.\\n\"\n",
    "        \"- \\\"Emotion\\\": A feeling (e.g., \\\"I felt overwhelmed\\\") — not a stance, but may influence one.\\n\\n\"\n",
    "        \"Known infant feeding targets:\\n\"\n",
    "        \"[\\\"breastfeeding\\\", \\\"formula feeding\\\", \\\"combo feeding\\\", \\\"bottle feeding\\\", \"\n",
    "        \"\\\"nursing\\\", \\\"pumping\\\", \\\"latching\\\", \\\"exclusive breastfeeding\\\", \\\"exclusive formula feeding\\\"]\\n\\n\"\n",
    "        f\"Text:\\n\\\"{text}\\\"\\n\\n\"\n",
    "        \"Instructions:\\n\"\n",
    "        \"1. Determine whether the text expresses a stance about an infant feeding method.\\n\"\n",
    "        \"2. If yes, return the matching target(s) from the list above.\\n\"\n",
    "        \"3. If no stance is present, indicate whether the text reflects behavior, emotion, or something else.\\n\\n\"\n",
    "        \"Return a JSON object in this format:\\n\"\n",
    "        \"{\\n\"\n",
    "        \"  \\\"Infant_Feeding_Targets\\\": [\\\"<target(s)>\\\"],\\n\"\n",
    "        \"  \\\"Stance\\\": \\\"<In Favor / Against / Neutral / Unclear>\\\",\\n\"\n",
    "        \"  \\\"Confidence\\\": <0–100>,\\n\"\n",
    "        \"  \\\"Reasoning\\\": \\\"<brief explanation>\\\",\\n\"\n",
    "        \"  \\\"Notes\\\": \\\"<e.g., behavior or emotion or something else>\\\"\\n\"\n",
    "        \"}\"\n",
    "    )\n",
    "    \n",
    "    result = classifier(prompt, max_new_tokens=400, temperature=0.0, do_sample=False)\n",
    "    response = result[0][\"generated_text\"].strip()  # no need for len(prompt) slice\n",
    "    \n",
    "    try:\n",
    "        parsed = json.loads(response)\n",
    "    except json.JSONDecodeError:\n",
    "        parsed = {\"error\": \"Invalid JSON\", \"raw_response\": response}\n",
    "    return parsed\n",
    "\n",
    "# ------------------------\n",
    "# Apply to dataset\n",
    "# ------------------------\n",
    "df[\"stance_result\"] = df[\"text\"].apply(classify_row)\n",
    "\n",
    "# Expand JSON dicts into separate columns\n",
    "df_expanded = pd.concat([df.drop(columns=[\"stance_result\"]), df[\"stance_result\"].apply(pd.Series)], axis=1)\n",
    "\n",
    "# ------------------------\n",
    "# Save outputs\n",
    "# ------------------------\n",
    "df_expanded.to_csv(\"classified_dataset.csv\", index=False)\n",
    "print(\"Done! Results saved to classified_dataset.csv\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
